codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto

ignore:
  - "examples/"
  - "LICENSE"
  - "README.md"
