codecov:
  enabled: true

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto
  
  exclude:
    - "examples/*"
    - "LICENSE"
    - "README.md"
