run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - revive
        - govet
      text: "ignore test files"

    - path: ^examples/
      linters:
        - errcheck
        - unused
        - revive
        - govet
      text: "ignore example code"
